name: info_pl
description: This Flutter plugin offers detailed information about the device's hardware, 
  operating system, phone model, platform version the app is running on, and more.
version: 0.0.3
repository: https://github.com/fadimanakilci/pl_plugins/tree/main/packages/info_pl
#issue_tracker: https://github.com/fadimanakilci/pl_plugins/labels/info_pl


environment:
  sdk: '>=3.1.3 <4.0.0'
  flutter: '>=3.3.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  logging: ^1.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  plugin:
    platforms:
      android:
        package: com.sparksign.info_pl
        pluginClass: InfoPlPlugin
      ios:
        pluginClass: InfoPlPlugin
      linux:
        pluginClass: InfoPlPlugin
      macos:
        pluginClass: InfoPlPlugin
      windows:
        pluginClass: InfoPlPluginCApi
      web:
        pluginClass: InfoPlWeb
        fileName: info_pl_web.dart

